### ISSUE TITLE
ODE Class Not Available

### ISSUE THREAD

**Issue by robbrit** [ossu/bioinformatics#18]
This course here is no longer available:
https://www.edx.org/course/introduction-differential-equations-bux-math226-1x-1

An alternative is available here:
https://ocw.mit.edu/courses/mathematics/18-03sc-differential-equations-fall-2011/
I've found it quite well organized, and the course videos are straight out of MIT's intro ODE class.

**Comment by eneskemalergin** [comment]
Thanks for catching the outdated link. I updated the README with the OCW link: e4baa2f
