### ISSUE TITLE
Replace BIO 1311

### ISSUE THREAD

**Issue by aweasadbek** [ossu/bioinformatics#23]
The vital part of the bioinformatics is a good knowledge of biology. It's very important for fundamental introductory courses to be in a very good quality. In my opinion it is impossible to learn biology without reading textbook. Of course lectures are important but text is far more. I'm currently learning my first "fundamental" course in Biology - it's not easy. To get a good grasp of every topic I'm taking three courses and reading two textbooks concurrently, and it does not feels overwhelming but instead helps a lot with understanding. 
So BIO 1311 "Introductory to Biology" fails to be a good fundamental course in a various aspects.
1. No textbook readings
2. No solutions to problem sets
3. No detailed explanation (this gap should filled with textbook). Many students cannot solve the problems given in the course, which would lead to frustration and anxiety. Students would think that they are not "good" enough to study biology. 

Overall BIO1311 is a good course for non biology major. I think to be a good curriculum in bioinformatics either one of this should be done with OSSU's curriculum:
a) replace [Introduction to Biology - The Secret of Life](https://www.edx.org/course/introduction-biology-secret-life-mitx-7-00x-2) with [ Introductory Biology 7.016](https://ocw.mit.edu/courses/biology/7-016-introductory-biology-fall-2018/index.htm) 
b) just add [ Introductory Biology 7.016](https://ocw.mit.edu/courses/biology/7-016-introductory-biology-fall-2018/index.htm) to the curriculum

[Fundamentals of Biology](https://ocw.mit.edu/courses/biology/7-01sc-fundamentals-of-biology-fall-2011/) is a course offered in MIT campus in Fall 2018 (which means it's relatively new). It's based on a good textbook (which I'm using), even if something won't be clear from lecture there's always a required reading where you will understand what you want.
7.016 contains detailed calendar when to read and when to solve problem sets in case you need one.
It has good quality problem sets and recitations (which are basically summaries and problems).
And recorded lectures which are also not bad.
Students will get a deeper understanding of each topic from 7.016 which would make them love and appreaciate biology. 
The proposed course is much more rigorous but it's worth time spent.

**Comment by aweasadbek** [comment]
If you think that 7.016 does not fits, I can create a reading list for each topic in https://www.edx.org/course/introduction-biology-secret-life-mitx-7-00x-2 from free online textbook. Also add problem sets from above mentioned 7.016

**Comment by AaishaMuhammad** [comment]
Perhaps we can add the proposed course instead of replacing BIO 1311? This was the first biology course I've done, and I think it lays down the foundations in an irreplaceable manner. I did not feel the lack of textbooks as any loss - the lectures were clear enough to make up for it, and I think it serves as an excellent starting point. Maybe your course can be added after that, for a more in-depth coverage of the topics?

**Comment by aweasadbek** [comment]
The content of two courses overlap hugely. It could be an alternative course but not the one which should be taken after "The secret of life".
