### ISSUE TITLE
RFC: Replace the current Calculus course

### ISSUE THREAD

**Issue by aweasadbek** [ossu/bioinformatics#24]
Current MATH 1313, MATH 1314, MATH 2311 courses by Robert Ghrist requires familiarity with limits, derivatives as stated in the beginning of that course. I tried to take that course but I could not do that as a beginner. All three course should be replaces by [Calculus 1A: Differentiation](https://www.edx.org/course/calculus-1a-differentiation), [Calculus 1B: Integration](https://www.edx.org/course/calculus-1b-integration), [Calculus 1C: Coordinate Systems & Infinite Series](https://www.edx.org/course/calculus-1c-coordinate-systems-infinite-series) respectively. Otherwise most people would stuck or even give up at calculus section of curriculum

**Comment by waciumawanjohi** [comment]
The Computer Science OSSU community has spent a significant amount of time discussing the best Calculus option.
Here are two relevant threads:
https://github.com/ossu/computer-science/issues/465
https://github.com/ossu/computer-science/issues/689

For the last few years we have used MIT's Calculus courses on edX. These are the courses that @aweasadbek is recommending.

**Comment by waciumawanjohi** [comment]
Resolved by https://github.com/ossu/bioinformatics/commit/918ec3ce26aee9a548c07df4c3829406acf720c2
