### ISSUE TITLE
Link to Introduction to databases is moved

### ISSUE THREAD

**Issue by PKatarina** [ossu/bioinformatics#26]
The course COMP 2312 is now moved into another site (edX) and it is segmented into 5 2-week courses. I guess :smile_cat: , didn't take the course yet

Edit:
The link from the curriculum is [this](https://online.stanford.edu/lagunita-learning-platform)
And if you follow the link to the edX page and search there for "introduction database" it will show the 5 courses from Stanford that I am guessing where in the original link.

**Comment by waciumawanjohi** [comment]
Resolved by https://github.com/ossu/bioinformatics/commit/21dc32747e427a930174f2a52d106dd81e3f05e3
