### ISSUE TITLE
Newer version of intro chemistry

### ISSUE THREAD

**Issue by memcardio** [ossu/bioinformatics#27]
Is it intentional that the link points to the [2008 class](https://ocw.mit.edu/courses/chemistry/5-111-principles-of-chemical-science-fall-2008/index.htm) rather than the [2014 class](https://ocw.mit.edu/courses/chemistry/5-111sc-principles-of-chemical-science-fall-2014/index.htm)? It kinda sounds like 2008 has more bio examples but it's also missing problem sets (unless I just suck at finding them).

**Comment by waciumawanjohi** [comment]
The original author of the curriculum has not participated in over a year, so there may not be a forthcoming answer to your question. If you think that the class should be changed, I encourage you to open a Request for Comment. You can find many examples of Requests For Comments in the CS Issues. [Here is an example](https://github.com/ossu/computer-science/issues/693).

Laying out the advantages and disadvantages to a change will be a great start to the conversation. All supporting evidence for those advantages and disadvantages will be helpful for commenters.

**Comment by memcardio** [comment]
Thanks for the quick reply :)

I'll create this issue later tonight and close this one with a link.
