### ISSUE TITLE
Consider adding "Intro to Protein Structure Prediction and Design including Review of Protein Structure" by Prof. Jeff Gray

### ISSUE THREAD

**Issue by LiorZ** [ossu/bioinformatics#32]
https://www.youtube.com/watch?v=TUyo8NFi_3Q&list=PLHn7WmALbthnAwbJ4mWw5gk8dgqsjRL87&ab_channel=Prof.JeffreyJ.GrayatJohnsHopkinsUniversity

**Comment by waciumawanjohi** [comment]
With no information on the value of adding this to the curriculum, I am closing this issue.

**Comment by waciumawanjohi** [comment]
Feel free to reopen with additional information. To be included in the curriculum, there should be justification for why an undergraduate degree in bioinformatics would be incomplete without the inclusion of this topic.

**Comment by LiorZ** [comment]
Hi,
Sorry for not providing more context, here is my take on the why it should be included:

Bioinformatics as a study subject has traditionally been about studying sequences of biomolecules (DNA/RNA/Protein) and their overall contribution to various cellular and organismal phenotypes. Not much emphasis has been given to studying in depth the 3-Dimensional structure of those biomolecules

A person looking at biomolecules from a 1D, sequence perspective would only get a limited view of the reasons sequence variations exert cellular and organismal variations. The ability to inspect biomolecules from a structural perspective and understand the intricacies of:

1. Hydrogen bond formation and disruption
2. Hydrophobicity and aggregation propensity
3. Ligand binding

and more, is essential to get a complete view of how various processes biology works and get disrupted down to the chemical/physical level.

The course attached is meant to provide students with this knowledge, and more. For example:
1. How one can view a protein (using pymol) and inspect various structural properties
2. Estimating (using Rosetta or other similar tools) the effect of a mutation on a protein foldability
3. Design of novel proteins and its contribution to synthetic enzymatic pathways (in the synthetic biology realm)

Additionally, the course will provide the student with the proper toolset to deepen her knowledge in the subject, learning more about recent advances in the field (e.g. AlphaFold)

Hope this helps!
This project is amazing.

**Comment by waciumawanjohi** [comment]
Lior,
This is a great deal of information, it's clear that you know this field. And to be clear, I do not. (I would very much like to find a qualified maintainer for this repository.)

The information you've provided demonstrates the value of this material. But that's slightly different from the question: "why would an undergraduate degree in bioinformatics be incomplete without the inclusion of this topic?"

To give an example, calculus is very valuable. But a 3rd grade math education is complete without teaching calculus. As justification I can point to the [Common Core curricular standards](https://www.education.com/common-core/third-grade/math/) (or standards from some other state/country).

[This issue](https://github.com/ossu/bioinformatics/issues/28) points to some efforts that we've found to specify what is necessary for a bioinformatics degree. Without a clear set of standards agreed upon by industry or academic accrediting bodies, coursework requirements listed by well respected universities can also demonstrate necessary topics.

Thank you for taking the time to work on improving this curriculum. OSSU only improves through the efforts of contributors like you!
