### ISSUE TITLE
A question 

### ISSUE THREAD

**Issue by SizifNoah** [ossu/bioinformatics#38]
according to the first 9 pages of the PDF in this link https://www.dna.caltech.edu/courses/cs191/paperscs191/gillespie1.pdf
I want the answer to this:-
![WhatsApp Image 2023-05-04 at 21 36 56](https://user-images.githubusercontent.com/129708156/236300896-26b4d31b-1b91-4d48-8ec5-ad91b0729d8c.jpg)

**Comment by waciumawanjohi** [comment]
The Github issues are meant to discuss problems with the curriculum or improvements to it. To work with fellow students on understanding material, I suggest checking out our Discord community, there's a channel for Bioinformatics.

Note that most of the OSSU community is studying the Computer Science curriculum. OSSU is happy to have had a contributor familiar with Bioinformatics and is happy to host this curriculum. If you or someone you know is able to support the maintenance of the curriculum or growth of the community, please feel free to reach out!
